"""Serena gateway: the harness owns, launches, and proxies the pinned Serena MCP server.

Single-server architecture: agents talk to one harness server; Serena's tools are
re-exposed here under the ``serena_`` prefix and forwarded over an MCP client
connection to a child Serena process. The child is launched lazily on the first
serena tool call (never at session start). The harness depends on the pinned
``serena-agent`` package (pyproject pins the same SHA as ``SERENA_PIN``) and launches
its ``serena`` console script from the harness venv — this module is the one and only
place the pin lives.

Lazy start works via a static tool snapshot: ``serena_tools.json`` (generated by
``repo-agent-harness gateway-snapshot`` against the pinned Serena, packaged with the
wheel) serves ``tools/list`` without touching the child. Because Serena is pinned
by commit SHA the snapshot is deterministic; a no-network test guards pin drift.

The stdio transport uses ``keep_alive``, so the Serena process (and its language
servers) survives across calls, and a crashed child is respawned transparently on
the next call.

The repo root is resolved **lazily**, on the first serena tool call — never at
construction. Callers pass either a fixed root string or a zero-arg callable that
returns the root at call time. This matters because the server process may be
started from a directory that is not the project (e.g. ``$HOME`` in a cloud
session): resolving at first use lets the child Serena attach to the real project
once the working directory / ``CLAUDE_PROJECT_DIR`` is settled.
"""

from __future__ import annotations

import json
import os
import sys
from contextlib import suppress
from importlib.resources import files
from pathlib import Path
from typing import TYPE_CHECKING

import anyio
from anyio import from_thread
from fastmcp import Client
from fastmcp.client.transports import StdioTransport
from fastmcp.tools import Tool, ToolResult
from mcp import types
from pydantic import PrivateAttr

from repo_agent_harness import serena_gate

if TYPE_CHECKING:
    from collections.abc import Callable

    import psutil

SERENA_PIN = "2449313c0d7427275c4c66aedff7d4881782f713"
SERENA_SPEC_ENV = "REPO_AGENT_HARNESS_SERENA_SPEC"
SERENA_CMD_ENV = "REPO_AGENT_HARNESS_SERENA_CMD"
SERENA_TIMEOUT_ENV = "REPO_AGENT_HARNESS_SERENA_TIMEOUT"
_DEFAULT_SERENA_TIMEOUT = 60.0
TOOL_PREFIX = "serena_"
_SNAPSHOT_NAME = "serena_tools.json"


def serena_spec() -> str:
    """Return the Serena git provenance spec recorded in the snapshot.

    Mirrors the pyproject ``serena-agent`` dependency; env-overridable.
    """
    return os.environ.get(SERENA_SPEC_ENV) or f"git+https://github.com/oraios/serena@{SERENA_PIN}"


def serena_timeout() -> float:
    """Return the per-call Serena timeout in seconds (env-overridable).

    Read at call time so tests can override it via the environment. A non-positive
    or unparseable override falls back to the default rather than failing the call.

    Returns:
        The timeout in seconds; the default when unset, empty, invalid, or <= 0.
    """
    raw = os.environ.get(SERENA_TIMEOUT_ENV)
    if not raw:
        return _DEFAULT_SERENA_TIMEOUT
    try:
        value = float(raw)
    except ValueError:
        return _DEFAULT_SERENA_TIMEOUT
    return value if value > 0 else _DEFAULT_SERENA_TIMEOUT


def serena_args(root: str) -> list[str]:
    """Return the argv (after the executable) to start the installed Serena MCP server."""
    return [
        "start-mcp-server",
        "--context",
        "claude-code",
        "--project",
        root,
        "--enable-web-dashboard",
        "false",
        "--enable-gui-log-window",
        "false",
    ]


def serena_command() -> str:
    """Resolve the Serena executable to launch.

    Serena ships as the ``serena-agent`` dependency, so its ``serena`` console script is
    installed next to the running interpreter (the harness venv). Prefer that path;
    honour an explicit env override (local Serena dev); fall back to the bare name on PATH.
    """
    override = os.environ.get(SERENA_CMD_ENV)
    if override:
        return override
    candidate = Path(sys.executable).parent / "serena"
    return str(candidate) if candidate.exists() else "serena"


def _is_stale_serena_child(cmdline: list[str], ours: str, root_resolved: str) -> bool:
    """True when ``cmdline`` is a Serena child for *this* repo launched by a *different* harness.

    Matches ``start-mcp-server --project <root>`` whose launching executable is not ``ours`` (the
    current venv's serena script). Same project + different binary ⇒ an orphan left by a prior
    plugin-cache version: ``keep_alive`` children outlive a SIGKILLed parent on upgrade. Excludes
    the user-level ``uvx ... --project-from-cwd`` Serena (it carries no ``--project``) and the
    current version's own child (``ours`` appears in its argv).
    """
    if "start-mcp-server" not in cmdline or "--project" not in cmdline:
        return False
    idx = cmdline.index("--project")
    if idx + 1 >= len(cmdline):
        return False
    proj = cmdline[idx + 1]
    try:
        same_project = str(Path(proj).resolve()) == root_resolved
    except OSError:
        same_project = proj == root_resolved
    return same_project and ours not in cmdline


def reap_stale_serena_children(root: str | None) -> list[int]:
    """Kill orphaned Serena children for this repo left behind by a previous harness version.

    Best-effort and deliberately narrow: only terminates processes whose ``--project`` is this
    repo and whose launcher is not the current version's serena. Never touches another project's
    Serena or the current child. Returns the reaped PIDs. A no-op when the serena command is a
    bare PATH name (versions are then indistinguishable) or psutil is unavailable.
    """
    if root is None:
        return []
    ours = serena_command()
    if os.sep not in ours:  # bare "serena" on PATH: can't tell versions apart — do nothing
        return []
    try:
        import psutil
    except ImportError:
        return []
    try:
        root_resolved = str(Path(root).resolve())
    except OSError:
        root_resolved = root
    victims = _stale_serena_procs(ours, root_resolved)
    for proc in victims:
        with suppress(psutil.Error):
            proc.terminate()
    _gone, alive = psutil.wait_procs(victims, timeout=2)
    for proc in alive:
        with suppress(psutil.Error):
            proc.kill()
    return [proc.pid for proc in victims]


def _stale_serena_procs(ours: str, root_resolved: str) -> list[psutil.Process]:
    """Return the live Serena children that are stale for this repo (skipping the current process)."""
    import psutil

    me = os.getpid()
    victims: list[psutil.Process] = []
    for proc in psutil.process_iter(["pid", "cmdline"]):
        if proc.pid == me:
            continue
        try:
            if _is_stale_serena_child(proc.info["cmdline"] or [], ours, root_resolved):
                victims.append(proc)
        except (psutil.Error, OSError):
            continue
    return victims


class SerenaGateway:
    """Lazy, crash-tolerant MCP client owning the child Serena process for one repo.

    Both the root resolution and the child connection are deferred to the first
    tool call: ``root`` may be a fixed string or a zero-arg callable resolved then.
    An injected ``transport`` (tests / dev) bypasses root resolution entirely.
    """

    def __init__(
        self,
        root: str | Callable[[], str | None],
        transport: StdioTransport | None = None,
    ) -> None:
        """Prepare the gateway without resolving the root or connecting.

        ``transport`` is injectable for tests; when given it is used as-is and the
        root is never resolved. Otherwise the client (and its child Serena) is built
        on the first call from the root resolved at that moment.
        """
        self._root_spec = root
        self._injected_transport = transport
        self._client: Client | None = None
        self._lock = anyio.Lock()
        self.root: str | None = root if isinstance(root, str) else None

    def _ensure_client(self) -> Client:
        """Build the client once, resolving the repo root lazily on first use."""
        if self._client is None:
            if self._injected_transport is not None:
                transport = self._injected_transport
            else:
                resolved = self._root_spec() if callable(self._root_spec) else self._root_spec
                self.root = resolved or str(Path.cwd())
                transport = StdioTransport(
                    command=serena_command(),
                    args=serena_args(self.root),
                    cwd=self.root,
                    keep_alive=True,
                )
            self._client = Client(transport)
        return self._client

    async def _connected_client(self) -> Client:
        """Return a live client, opening the session once and reusing it across calls.

        The session (and the child Serena plus its language servers) is entered a single
        time and held open for the gateway's lifetime, so sequential ``serena_*`` calls
        skip the per-call MCP ``initialize`` handshake that the old per-call ``async with``
        paid every time. A dead session (crash, or teardown after a timeout) is detected
        via ``is_connected()`` and transparently respawned on the next call.
        """
        async with self._lock:
            client = self._client
            if client is None or not client.is_connected():
                client = await self._open_locked()
            return client

    async def _open_locked(self) -> Client:
        """Discard any dead client, then build and connect a fresh one. Caller holds the lock."""
        await self._discard_locked()
        client = self._ensure_client()
        # Persistent session: enter the context once and keep it open across calls (closed in
        # _discard_locked), so we deliberately call the dunder instead of ``async with``.
        await client.__aenter__()  # noqa: PLC2801
        return client

    async def _discard_locked(self) -> None:
        """Tear down the current client so the next call reconnects cleanly. Caller holds the lock."""
        old, self._client = self._client, None
        if old is not None:
            with suppress(Exception):
                await old.close()

    async def _invalidate(self) -> None:
        """Drop a failed session so the next call respawns Serena (crash/timeout recovery)."""
        async with self._lock:
            await self._discard_locked()

    async def call(self, name: str, arguments: dict) -> types.CallToolResult:
        """Forward one tool call to Serena over the persistent session (launched on first use).

        The forwarded call is bounded by :func:`serena_timeout` so a hung or slow
        language-server call cannot block the harness indefinitely; on timeout or transport
        failure the session is invalidated so the next call reconnects a fresh child.

        Raises:
            TimeoutError: If Serena does not respond within the timeout.
        """
        client = await self._connected_client()
        try:
            with anyio.fail_after(serena_timeout()):
                return await client.call_tool_mcp(name, arguments)
        except TimeoutError:
            await self._invalidate()
            msg = f"serena call {name!r} timed out after {serena_timeout()}s"
            raise TimeoutError(msg) from None
        except BaseException:
            await self._invalidate()
            raise

    def call_from_thread(self, name: str, arguments: dict) -> types.CallToolResult:
        """Sync facade for callers running in a worker thread (e.g. health checks)."""
        return from_thread.run(self.call, name, arguments)

    async def list_live_tools(self) -> list[types.Tool]:
        """List tools from the live child (used by the snapshot generator)."""
        client = self._ensure_client()
        async with client:
            return await client.list_tools()

    async def aclose(self) -> None:
        """Terminate the child process, if one was ever started."""
        async with self._lock:
            await self._discard_locked()


class _ProxiedSerenaTool(Tool):
    """A snapshot-defined tool whose run() forwards to the gateway, result passed through verbatim."""

    _gateway: SerenaGateway = PrivateAttr()

    async def run(self, arguments: dict) -> ToolResult:
        """Forward to Serena and map the raw CallToolResult 1:1 (content, structured, is_error).

        First consult the per-file capability gate: a tool whose underlying LSP method is
        unsupported for the target file's language (e.g. find_implementations on Python, which
        Pyright does not implement) is refused here — before connecting — with a redirect message.
        """
        bare = self.name.removeprefix(TOOL_PREFIX)
        gate = serena_gate.capability_gate_for(bare)
        if gate is not None and not serena_gate.gate_disabled():
            refusal = gate(arguments.get("relative_path", ""))
            if refusal is not None:
                return ToolResult(content=[types.TextContent(type="text", text=refusal)], is_error=True)
        result = await self._gateway.call(bare, arguments)
        return ToolResult(
            content=result.content,
            structured_content=result.structuredContent,
            is_error=bool(result.isError),
        )


def load_snapshot() -> dict:
    """Load the packaged Serena tool snapshot, or an empty one when not generated yet."""
    resource = files("repo_agent_harness") / _SNAPSHOT_NAME
    if not resource.is_file():
        return {"pin": SERENA_PIN, "tools": []}
    return json.loads(resource.read_text(encoding="utf-8"))


def proxied_tools(gw: SerenaGateway) -> list[Tool]:
    """Build the prefixed, forwarding Tool objects from the static snapshot (no connection)."""
    tools: list[Tool] = []
    for entry in load_snapshot()["tools"]:
        tool = _ProxiedSerenaTool(
            name=TOOL_PREFIX + entry["name"],
            description=entry.get("description"),
            parameters=entry.get("inputSchema") or {"type": "object"},
            output_schema=entry.get("outputSchema"),
        )
        tool._gateway = gw
        tools.append(tool)
    return tools


def generate_snapshot(root: str) -> dict:
    """Launch the pinned Serena once, dump its tool list, and write the packaged snapshot.

    Dev-time command (network: resolves the pin). Returns a summary dict.
    """
    gw = SerenaGateway(root)

    async def _dump() -> list[types.Tool]:
        try:
            return await gw.list_live_tools()
        finally:
            await gw.aclose()

    tools = anyio.run(_dump)
    snapshot = {
        "pin": SERENA_PIN,
        "spec": serena_spec(),
        "tools": [t.model_dump(mode="json", exclude_none=True) for t in tools],
    }
    # dev-time command: writes into the source tree next to this module
    target = Path(__file__).parent / _SNAPSHOT_NAME
    target.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")
    return {"ok": True, "pin": SERENA_PIN, "tool_count": len(tools), "written": str(target)}
