"""Serena gateway: the harness owns, launches, and proxies the pinned Serena MCP server.

Single-server architecture: agents talk to one harness server; Serena's tools are
re-exposed here under the ``serena_`` prefix and forwarded over an MCP client
connection to a child Serena process. The child is launched lazily on the first
serena tool call (never at session start). The harness depends on the pinned
``serena-agent`` package (pyproject pins the same SHA as ``SERENA_PIN``) and launches
its ``serena`` console script from the harness venv — this module is the one and only
place the pin lives.

Lazy start works via a static tool snapshot: ``serena_tools.json`` (generated by
``repo-agent-harness gateway-snapshot`` against the pinned Serena, packaged with the
wheel) serves ``tools/list`` without touching the child. Because Serena is pinned
by commit SHA the snapshot is deterministic; a no-network test guards pin drift.

The stdio transport uses ``keep_alive``, so the Serena process (and its language
servers) survives across calls, and a crashed child is respawned transparently on
the next call.

The repo root is resolved **lazily**, on the first serena tool call — never at
construction. Callers pass either a fixed root string or a zero-arg callable that
returns the root at call time. This matters because the server process may be
started from a directory that is not the project (e.g. ``$HOME`` in a cloud
session): resolving at first use lets the child Serena attach to the real project
once the working directory / ``CLAUDE_PROJECT_DIR`` is settled.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import threading
import time
from contextlib import contextmanager, suppress
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path
from typing import TYPE_CHECKING

import anyio
from anyio import from_thread, to_thread
from fastmcp import Client
from fastmcp.client.transports import StdioTransport
from fastmcp.tools import Tool, ToolResult
from mcp import types
from pydantic import PrivateAttr

from repo_agent_harness import serena_gate

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator

    import psutil

SERENA_PIN = "2449313c0d7427275c4c66aedff7d4881782f713"
SERENA_SPEC_ENV = "REPO_AGENT_HARNESS_SERENA_SPEC"
SERENA_CMD_ENV = "REPO_AGENT_HARNESS_SERENA_CMD"
SERENA_TIMEOUT_ENV = "REPO_AGENT_HARNESS_SERENA_TIMEOUT"
SERENA_CONNECT_TIMEOUT_ENV = "REPO_AGENT_HARNESS_SERENA_CONNECT_TIMEOUT"
SERENA_CLOSE_TIMEOUT_ENV = "REPO_AGENT_HARNESS_SERENA_CLOSE_TIMEOUT"
SERENA_DISPATCH_TIMEOUT_ENV = "REPO_AGENT_HARNESS_SERENA_DISPATCH_TIMEOUT"
SERENA_HARD_DEADLINE_ENV = "REPO_AGENT_HARNESS_SERENA_HARD_DEADLINE"
_DEFAULT_SERENA_TIMEOUT = 60.0
# Connecting spawns Serena and boots one language server per seeded language
# (see context.serena_languages) — a cold multi-LSP startup far slower than a steady-state
# call, so it gets its own, more generous budget. Without bounding it the first call's connect
# was unbounded and could hang until the agent was killed.
_DEFAULT_SERENA_CONNECT_TIMEOUT = 120.0
# Bounds tearing down a (possibly wedged) client in _discard_locked. The teardown runs under
# self._lock, so an unbounded close() on a child whose teardown never returns wedges the lock
# and every concurrent caller hangs at ``async with self._lock``. Generous enough that a healthy
# close is never cut short; a timed-out close is abandoned (the child is reaped at next startup).
_DEFAULT_SERENA_CLOSE_TIMEOUT = 10.0
# Grace above serena_timeout() before the out-of-band watchdog force-kills a child whose stdio
# read wedged mid-request (issue #30): the cooperative fail_after cannot unwind that await, so an
# independent timer kills the child's process group from the outside. Kept relative to the per-call
# timeout so tests that lower only SERENA_TIMEOUT_ENV don't arm an absolute hard kill.
_DEFAULT_SERENA_HARD_DEADLINE_GRACE = 15.0
# SIGTERM→SIGKILL escalation gap inside _kill_child_group (a wedged child rarely honours SIGTERM).
_HARD_KILL_GRACE_SECONDS = 0.5
TOOL_PREFIX = "serena_"
_SNAPSHOT_NAME = "serena_tools.json"


def serena_spec() -> str:
    """Return the Serena git provenance spec recorded in the snapshot.

    Mirrors the pyproject ``serena-agent`` dependency; env-overridable.
    """
    return os.environ.get(SERENA_SPEC_ENV) or f"git+https://github.com/oraios/serena@{SERENA_PIN}"


def _positive_float_env(name: str, default: float) -> float:
    """Return a positive float from env ``name``, falling back to ``default``.

    Read at call time so tests can override it via the environment. A non-positive,
    empty, or unparseable value falls back to the default rather than failing the call.
    """
    raw = os.environ.get(name)
    if not raw:
        return default
    try:
        value = float(raw)
    except ValueError:
        return default
    return value if value > 0 else default


def serena_timeout() -> float:
    """Return the per-call Serena timeout in seconds (env-overridable)."""
    return _positive_float_env(SERENA_TIMEOUT_ENV, _DEFAULT_SERENA_TIMEOUT)


def serena_hard_deadline() -> float:
    """Return the out-of-band hard-kill deadline in seconds (env-overridable grace).

    Sits a fixed grace *above* :func:`serena_timeout` so it only ever fires when the cooperative
    per-call timeout failed to unwind a wedged stdio read (issue #30) — a child that stops
    answering mid-request, where ``anyio.fail_after``'s cancellation never reaches the blocked
    await. Kept timeout-relative (not absolute) so a test that lowers only ``SERENA_TIMEOUT_ENV``
    does not accidentally arm a hard kill that perturbs its cooperative-recovery assertions;
    ``REPO_AGENT_HARNESS_SERENA_HARD_DEADLINE`` overrides the grace, not the total.
    """
    grace = _positive_float_env(SERENA_HARD_DEADLINE_ENV, _DEFAULT_SERENA_HARD_DEADLINE_GRACE)
    return serena_timeout() + grace


def serena_connect_timeout() -> float:
    """Return the session connect/startup timeout in seconds (env-overridable).

    Bounds the one-time spawn + MCP ``initialize`` + language-server boot in
    :meth:`SerenaGateway._open_locked`; more generous than :func:`serena_timeout`
    because a cold multi-LSP start is slow.
    """
    return _positive_float_env(SERENA_CONNECT_TIMEOUT_ENV, _DEFAULT_SERENA_CONNECT_TIMEOUT)


def serena_connect_hard_deadline() -> float:
    """Return the out-of-band connect hard-kill deadline in seconds (env-overridable grace).

    The connect-time analogue of :func:`serena_hard_deadline`: a grace *above*
    :func:`serena_connect_timeout`, fired only when a child wedges mid-initialize with a
    cancellation-deaf stdio read (issue #30 at connect time) — where ``anyio.fail_after`` cannot
    unwind the blocked ``__aenter__`` and ``_child_pid`` is not set yet, so the per-call dispatch
    watchdog never arms. Shares the ``REPO_AGENT_HARNESS_SERENA_HARD_DEADLINE`` grace and stays
    connect-timeout-relative, so a test lowering only the connect timeout never arms a stray kill.
    """
    grace = _positive_float_env(SERENA_HARD_DEADLINE_ENV, _DEFAULT_SERENA_HARD_DEADLINE_GRACE)
    return serena_connect_timeout() + grace


def serena_close_timeout() -> float:
    """Return the per-teardown close timeout in seconds (env-overridable).

    Bounds ``await old.close()`` in :meth:`SerenaGateway._discard_locked`, which runs under
    the gateway lock: an unbounded close on a wedged child would hold the lock forever and
    block every concurrent ``serena_*`` caller. A timed-out close is abandoned, not retried.
    """
    return _positive_float_env(SERENA_CLOSE_TIMEOUT_ENV, _DEFAULT_SERENA_CLOSE_TIMEOUT)


def serena_dispatch_timeout() -> float:
    """Return the whole-dispatch deadline in seconds for one :meth:`SerenaGateway.call`.

    Bounds the *entire* dispatch — the connect/lock-wait plus the forwarded call — so a wedged
    lock or stuck connect can never leave a single dispatch "still running" forever (the host
    heartbeat never stops). Defaults to ``serena_connect_timeout() + serena_timeout()`` so a
    legitimate cold multi-LSP boot followed by one call never trips it; env-overridable.
    """
    raw = os.environ.get(SERENA_DISPATCH_TIMEOUT_ENV)
    if raw:
        try:
            value = float(raw)
        except ValueError:
            value = 0.0
        if value > 0:
            return value
    # Read the two sub-budgets straight from the env (not via serena_connect_timeout/
    # serena_timeout) so the default tracks env overrides without being perturbed by tests that
    # monkeypatch those wrapper *functions* statefully — a stray re-read would desync them.
    connect = _positive_float_env(SERENA_CONNECT_TIMEOUT_ENV, _DEFAULT_SERENA_CONNECT_TIMEOUT)
    call = _positive_float_env(SERENA_TIMEOUT_ENV, _DEFAULT_SERENA_TIMEOUT)
    return connect + call


TOOL_TIMEOUT_ENV = "REPO_AGENT_HARNESS_TOOL_TIMEOUT"
# The generic-tool middleware backstop must never fire before Serena's own dispatch reap, or it
# would pre-empt the carefully scoped Serena teardown (a serena_* call routes through BOTH this
# middleware and the gateway, so its budget must sit clear above serena_dispatch_timeout()'s
# default of connect(120) + call(60) = 180s). 240s leaves a comfortable margin while still
# guaranteeing the host heartbeat is never starved by a wedged generic handler (file/grep/shell).
_DEFAULT_TOOL_TIMEOUT = 240.0


def tool_timeout() -> float:
    """Return the generic-tool dispatch backstop timeout in seconds (env-overridable).

    Bounds every ``@mcp.tool`` handler via the server middleware so a runaway generic tool
    (file read, grep, shell) cannot block the harness indefinitely. A pure backstop: the
    default deliberately stays clear of Serena's own per-dispatch reap so it never pre-empts it.
    """
    return _positive_float_env(TOOL_TIMEOUT_ENV, _DEFAULT_TOOL_TIMEOUT)


class ToolTimeoutError(Exception):
    """Raised when a generic tool dispatch exceeds :func:`tool_timeout`.

    Carries the offending ``tool`` name and the ``timeout_s`` deadline that was exceeded so
    callers (and structured logs) can report exactly which handler was reaped and at what budget.
    """

    def __init__(self, *, tool: str, timeout_s: float) -> None:
        """Record the offending ``tool`` and the ``timeout_s`` deadline it exceeded."""
        self.tool = tool
        self.timeout_s = timeout_s
        super().__init__(f"tool {tool!r} exceeded its {timeout_s}s dispatch timeout")


def serena_args(root: str) -> list[str]:
    """Return the argv (after the executable) to start the installed Serena MCP server."""
    return [
        "start-mcp-server",
        "--context",
        "claude-code",
        "--project",
        root,
        "--enable-web-dashboard",
        "false",
        "--enable-gui-log-window",
        "false",
    ]


def serena_command() -> str:
    """Resolve the Serena executable to launch.

    Serena ships as the ``serena-agent`` dependency, so its ``serena`` console script is
    installed next to the running interpreter (the harness venv). Prefer that path;
    honour an explicit env override (local Serena dev); fall back to the bare name on PATH.
    """
    override = os.environ.get(SERENA_CMD_ENV)
    if override:
        return override
    candidate = Path(sys.executable).parent / "serena"
    return str(candidate) if candidate.exists() else "serena"


def _is_stale_serena_child(cmdline: list[str], ours: str, root_resolved: str) -> bool:
    """True when ``cmdline`` is a Serena child for *this* repo launched by a *different* harness.

    Matches ``start-mcp-server --project <root>`` whose launching executable is not ``ours`` (the
    current venv's serena script). Same project + different binary ⇒ an orphan left by a prior
    plugin-cache version: ``keep_alive`` children outlive a SIGKILLed parent on upgrade. Excludes
    the user-level ``uvx ... --project-from-cwd`` Serena (it carries no ``--project``) and the
    current version's own child (``ours`` appears in its argv).
    """
    if "start-mcp-server" not in cmdline or "--project" not in cmdline:
        return False
    idx = cmdline.index("--project")
    if idx + 1 >= len(cmdline):
        return False
    proj = cmdline[idx + 1]
    try:
        same_project = str(Path(proj).resolve()) == root_resolved
    except OSError:
        same_project = proj == root_resolved
    return same_project and ours not in cmdline


def reap_stale_serena_children(root: str | None) -> list[int]:
    """Kill orphaned Serena children for this repo left behind by a previous harness version.

    Best-effort and deliberately narrow: only terminates processes whose ``--project`` is this
    repo and whose launcher is not the current version's serena. Never touches another project's
    Serena or the current child. Returns the reaped PIDs. A no-op when the serena command is a
    bare PATH name (versions are then indistinguishable) or psutil is unavailable.
    """
    if root is None:
        return []
    ours = serena_command()
    if os.sep not in ours:  # bare "serena" on PATH: can't tell versions apart — do nothing
        return []
    try:
        import psutil
    except ImportError:
        return []
    try:
        root_resolved = str(Path(root).resolve())
    except OSError:
        root_resolved = root
    victims = _stale_serena_procs(ours, root_resolved)
    for proc in victims:
        with suppress(psutil.Error):
            proc.terminate()
    _gone, alive = psutil.wait_procs(victims, timeout=2)
    for proc in alive:
        with suppress(psutil.Error):
            proc.kill()
    return [proc.pid for proc in victims]


def _stale_serena_procs(ours: str, root_resolved: str) -> list[psutil.Process]:
    """Return the live Serena children that are stale for this repo (skipping the current process)."""
    import psutil

    me = os.getpid()
    victims: list[psutil.Process] = []
    for proc in psutil.process_iter(["pid", "cmdline"]):
        if proc.pid == me:
            continue
        try:
            if _is_stale_serena_child(proc.info["cmdline"] or [], ours, root_resolved):
                victims.append(proc)
        except (psutil.Error, OSError):
            continue
    return victims


def _direct_child_pids() -> set[int]:
    """Return the PIDs of this process's direct children (empty if psutil is unavailable).

    Snapshotted just before a connect so :func:`_discover_child_pid` can diff out the freshly
    spawned Serena child — fastmcp keeps the child PID closure-local in ``stdio_client`` and never
    exposes it, so the gateway recovers it out-of-band by this children-diff.
    """
    try:
        import psutil
    except ImportError:
        return set()
    try:
        return {child.pid for child in psutil.Process().children()}
    except psutil.Error:
        return set()


def _discover_child_pid(before: set[int]) -> int | None:
    """Return the PID of the Serena child that appeared since the ``before`` snapshot.

    Diffs the current direct children against ``before`` (taken before the connect): the new
    direct child is the Serena process. Its process group — killed via :func:`_kill_child_group`
    — also reaps the language-server grandchildren spawned later. ``None`` when psutil is
    unavailable or no new child appeared (e.g. an injected in-process transport).
    """
    new = _direct_child_pids() - before
    return min(new) if new else None


def _kill_child_group(pid: int) -> None:
    """Force-kill the process group led by ``pid`` (SIGTERM, brief grace, then SIGKILL).

    The Serena child is spawned by mcp's stdio client with ``start_new_session=True``, so it leads
    its own process group; killing the group reaps the child and its language-server grandchildren.
    This is the only thing that unwedges a child whose stdio read ignores the cooperative
    ``fail_after`` (issue #30): the kill closes the child's stdout, so the blocked harness-side
    read finally errors out. Idempotent and best-effort — ``getpgid``/``killpg`` on an
    already-exited group raise a suppressed ``ProcessLookupError`` — so it is safe to call on the
    clean-close path too. Runs synchronously (offloaded to a thread by its async callers so the
    short SIGTERM→SIGKILL grace never blocks the event loop).
    """
    import signal

    with suppress(ProcessLookupError, PermissionError, OSError):
        pgid = os.getpgid(pid)
        os.killpg(pgid, signal.SIGTERM)
        time.sleep(_HARD_KILL_GRACE_SECONDS)
        with suppress(ProcessLookupError, PermissionError, OSError):
            os.killpg(pgid, signal.SIGKILL)


# Consecutive per-call timeouts (with no intervening success) after which the shared Serena
# child is treated as wedged and respawned, even while it still reports connected. ``is_connected``
# lags a dead child, and a hung language server can hold the connection open yet never answer, so
# without this a wedged child would time out every call forever; with it, recovery is restored
# without letting a single slow call tear the session out from concurrent siblings.
_WEDGE_TIMEOUTS = 3

# Elapsed seconds after which an in-flight tool call is flagged ``stalled`` in the diagnostics
# snapshot. Purely advisory (diagnostics #26): it never cancels anything — the tool_timeout()
# middleware owns cancellation — it only surfaces "this call has been running suspiciously long".
_INFLIGHT_STALL_SECONDS = 120.0


def _inflight_clock() -> float:
    """Monotonic clock for in-flight elapsed timing (patchable in tests)."""
    return time.monotonic()


@dataclass(frozen=True)
class _InFlight:
    """One tracked, currently-executing tool dispatch."""

    tool: str
    cwd: str
    started_monotonic: float


class SerenaGateway:
    """Lazy, crash-tolerant MCP client owning the child Serena process for one repo.

    Both the root resolution and the child connection are deferred to the first
    tool call: ``root`` may be a fixed string or a zero-arg callable resolved then.
    An injected ``transport`` (tests / dev) bypasses root resolution entirely.
    """

    def __init__(
        self,
        root: str | Callable[[], str | None],
        transport: StdioTransport | None = None,
    ) -> None:
        """Prepare the gateway without resolving the root or connecting.

        ``transport`` is injectable for tests; when given it is used as-is and the
        root is never resolved. Otherwise the client (and its child Serena) is built
        on the first call from the root resolved at that moment.
        """
        self._root_spec = root
        self._injected_transport = transport
        self._client: Client | None = None
        self._lock = anyio.Lock()
        # Single-flight cold-connect task, shared by every caller that arrives while a connect
        # is in flight. Detached from any one caller's cancel scope so a caller cancelled
        # mid-connect cannot tear the shared, in-progress connect (and its freshly spawned
        # child) down — that was the parallel-subagent respawn storm.
        self._connect_task: asyncio.Task[Client] | None = None
        self._consecutive_timeouts = 0
        # PID of the live child Serena process, captured out-of-band at connect (fastmcp never
        # exposes it). The out-of-band watchdog and teardown escalation kill its process group to
        # unwedge / reap a child whose stdio read ignores the cooperative timeout (issue #30).
        self._child_pid: int | None = None
        self.root: str | None = root if isinstance(root, str) else None
        # In-flight registry (diagnostics #26): the single source of truth for *every* currently
        # executing tool dispatch — both serena_* forwards (registered in ``call``) and generic
        # tools (registered by the server middleware). Guarded by a plain threading.Lock because
        # the sync snapshot is read from worker threads (health checks) while async callers mutate
        # it; the critical sections are O(1) dict ops, so the lock is never contended for long.
        self._in_flight: dict[int, _InFlight] = {}
        self._in_flight_lock = threading.Lock()
        self._in_flight_seq = 0

    def warm(self) -> asyncio.Task[Client]:
        """Eagerly start the shared Serena session in the background.

        Tool calls that arrive while the connect is in flight coalesce onto the
        same single-flight connect, so pre-warming during server startup removes
        the user-visible cold-boot pause from the first ``serena_*`` call.
        """
        task = asyncio.ensure_future(self._connected_client())
        # Suppress "exception was never retrieved" if the task fails before any caller awaits it.
        task.add_done_callback(lambda t: t.cancelled() or t.exception())
        return task

    def _ensure_client(self) -> Client:
        """Build the client once, resolving the repo root lazily on first use."""
        if self._client is None:
            if self._injected_transport is not None:
                transport = self._injected_transport
            else:
                resolved = self._root_spec() if callable(self._root_spec) else self._root_spec
                self.root = resolved or str(Path.cwd())
                transport = StdioTransport(
                    command=serena_command(),
                    args=serena_args(self.root),
                    cwd=self.root,
                    keep_alive=True,
                )
            self._client = Client(transport)
        return self._client

    async def _connected_client(self) -> Client:
        """Return a live client, opening the session once and reusing it across calls.

        The session (and the child Serena plus its language servers) is entered a single
        time and held open for the gateway's lifetime, so sequential ``serena_*`` calls
        skip the per-call MCP ``initialize`` handshake that the old per-call ``async with``
        paid every time. A dead session (crash, or teardown after a timeout) is detected
        via ``is_connected()`` and transparently respawned on the next call.

        The cold connect runs as a **single-flight, detached task** awaited through
        ``asyncio.shield``: concurrent first-callers coalesce onto one connect (no thundering
        herd of children), and — critically — a caller cancelled mid-connect only stops
        *awaiting*; the connect itself runs to completion for its siblings and its own retry.
        Without this a cancelled cold connect let fastmcp force-close the half-open child, so
        every cancelled attempt spawned and immediately killed a Serena child — the respawn
        storm that hung parallel subagents.
        """
        async with self._lock:
            client = self._client
            if client is not None and client.is_connected():
                return client
            task = self._connect_task
            if task is None or task.done():
                task = asyncio.ensure_future(self._connect_once())
                # Retrieve the result even if every awaiter is cancelled, so a failed connect
                # with no surviving caller never logs "exception was never retrieved".
                task.add_done_callback(lambda t: t.cancelled() or t.exception())
                self._connect_task = task
        return await asyncio.shield(task)

    async def _connect_once(self) -> Client:
        """Connect (or reconnect) the shared session — the single-flight body.

        Dispatched as a detached task by :meth:`_connected_client` so no individual caller's
        cancellation can interrupt it. Holds the lock for the connect's duration so it never
        races a concurrent discard/reap, and is bounded by :func:`serena_connect_timeout`
        inside :meth:`_open_locked`.
        """
        async with self._lock:
            return await self._open_locked()

    async def _open_locked(self) -> Client:
        """Discard any dead client, then build and connect a fresh one. Caller holds the lock.

        The connect (spawn + MCP ``initialize`` + language-server boot) is bounded by
        :func:`serena_connect_timeout`; without it a slow/stuck startup could hang
        unbounded and, since the caller holds the lock, wedge every other ``serena_*`` call.
        On timeout the half-opened client is discarded so the next call respawns cleanly
        (fastmcp reaps the spawned child on the cancellation that ``fail_after`` raises).

        That cooperative bound is not enough on its own: a child that wedges *mid-initialize* with
        a cancellation-deaf stdio read (issue #30, at connect time) never lets ``fail_after`` unwind
        the blocked ``__aenter__``, and no PID is captured yet, so the per-call dispatch watchdog
        never arms — an unbounded first-call hang (the live ``serena_initial_instructions`` stall).
        An out-of-band **connect watchdog** closes that gap: armed at
        :func:`serena_connect_hard_deadline`, it discovers the freshly spawned child by diffing the
        pre-spawn snapshot and force-kills its process group, closing the child's stdout so the
        blocked connect read errors out and ``__aenter__`` unwinds here. ``hard_killed`` records
        that we caused it, so whichever exception the unwinding read surfaces (a transport error, a
        converted ``TimeoutError``, or a stray cancellation) is normalized to a ``TimeoutError`` and
        the dead half-open session discarded — the next call respawns a fresh child.
        """
        await self._discard_locked()
        client = self._ensure_client()
        budget = serena_connect_timeout()
        # Snapshot our direct children before the spawn so the freshly launched Serena child can be
        # identified by diff (fastmcp keeps its PID closure-local): the watchdog gets a process
        # group to kill if this child wedges mid-connect, and the success path seeds _child_pid.
        before = _direct_child_pids()
        hard_killed = False

        async def _connect_watchdog() -> None:
            # Independent of the cooperative connect fail_after a mid-initialize wedge ignores: sleep
            # past the connect hard deadline, then kill the child's process group so its stdout closes
            # and the blocked __aenter__ read unwinds. The child is spawned before the initialize
            # handshake, so it is already a visible direct child though __aenter__ has not returned;
            # discover it by the same children-diff and record the PID so the discard does not leak it.
            nonlocal hard_killed
            await anyio.sleep(serena_connect_hard_deadline())
            pid = _discover_child_pid(before)
            if pid is None:
                return
            hard_killed = True
            self._child_pid = pid
            await to_thread.run_sync(_kill_child_group, pid)

        watchdog = asyncio.ensure_future(_connect_watchdog())
        try:
            with anyio.fail_after(budget):
                await client.__aenter__()  # noqa: PLC2801
        except TimeoutError:
            await self._discard_locked()
            msg = (
                f"serena connect hard-killed after {serena_connect_hard_deadline()}s (wedged mid-connect)"
                if hard_killed
                else f"serena connect timed out after {budget}s"
            )
            raise TimeoutError(msg) from None
        except anyio.get_cancelled_exc_class():
            if hard_killed:
                await self._discard_locked()
                msg = f"serena connect hard-killed after {serena_connect_hard_deadline()}s (wedged mid-connect)"
                raise TimeoutError(msg) from None
            raise
        except BaseException:
            if hard_killed:
                await self._discard_locked()
                msg = f"serena connect hard-killed after {serena_connect_hard_deadline()}s (wedged mid-connect)"
                raise TimeoutError(msg) from None
            raise
        finally:
            watchdog.cancel()
            with suppress(BaseException):
                await watchdog
        self._child_pid = _discover_child_pid(before)
        return client

    async def _discard_locked(self) -> None:
        """Tear down the current client so the next call reconnects cleanly. Caller holds the lock."""
        old, self._client = self._client, None
        pid, self._child_pid = self._child_pid, None
        if old is not None:
            # Bound the teardown: ``self._client`` is already nulled, so a close that never
            # returns must not hold the lock forever (that wedges every concurrent caller).
            # ``anyio.fail_after`` raises builtin ``TimeoutError`` (an ``Exception``) which the
            # surrounding ``suppress`` swallows, abandoning a hung close after the budget.
            with suppress(Exception), anyio.fail_after(serena_close_timeout()):
                await old.close()
        # A wedged ``close()`` is abandoned above, leaking the child; force-kill its process group
        # so a reaped child is actually gone, not orphaned. Offloaded to a thread so the
        # SIGTERM→SIGKILL grace can't block the loop; idempotent/suppressed, so it is harmless on
        # the clean-close path (the child is already dead → killpg no-ops).
        if pid is not None:
            await to_thread.run_sync(_kill_child_group, pid)

    async def _reap_if_current(self, client: Client) -> None:
        """Discard the shared session iff it is still the one ``client`` refers to.

        Gating on identity means a burst of callers that all fail on the same dead/wedged child
        respawns it exactly once: the first reaper discards it; a later reaper whose ``client``
        no longer matches ``self._client`` (someone already reconnected) is a no-op, so the
        freshly spawned child is never thrashed. The next :meth:`_connected_client` reconnects.
        """
        async with self._lock:
            if self._client is client:
                await self._discard_locked()
                self._consecutive_timeouts = 0

    @contextmanager
    def register_inflight(self, tool: str, cwd: str) -> Iterator[None]:
        """Track ``tool`` (running in ``cwd``) for the body's duration, then drop it.

        The single registration point for the in-flight diagnostics registry: the server
        middleware wraps every generic ``@mcp.tool`` dispatch with it, and :meth:`call` wraps the
        serena_* forward. Removal happens in ``finally`` so a raising or cancelled body never
        leaks a phantom entry.
        """
        with self._in_flight_lock:
            self._in_flight_seq += 1
            token = self._in_flight_seq
            self._in_flight[token] = _InFlight(tool=tool, cwd=cwd, started_monotonic=_inflight_clock())
        try:
            yield
        finally:
            with self._in_flight_lock:
                self._in_flight.pop(token, None)

    def in_flight_snapshot(self) -> list[dict]:
        """Return a sync snapshot of every currently-executing tool dispatch.

        Each entry is ``{tool, cwd, elapsed_s, stalled}`` where ``elapsed_s`` is monotonic
        wall-time since registration and ``stalled`` is ``elapsed_s > _INFLIGHT_STALL_SECONDS``.
        Safe to call from a worker thread (health checks); takes a point-in-time copy under the
        lock so a concurrent register/deregister cannot tear iteration.
        """
        now = _inflight_clock()
        with self._in_flight_lock:
            entries = list(self._in_flight.values())
        out: list[dict] = []
        for entry in entries:
            elapsed = now - entry.started_monotonic
            out.append(
                {
                    "tool": entry.tool,
                    "cwd": entry.cwd,
                    "elapsed_s": elapsed,
                    "stalled": elapsed > _INFLIGHT_STALL_SECONDS,
                }
            )
        return out

    async def call(self, name: str, arguments: dict) -> types.CallToolResult:
        """Forward one tool call to Serena over the persistent session (launched on first use).

        The forwarded call is bounded by :func:`serena_timeout` so a hung or slow
        language-server call cannot block the harness indefinitely.

        The session is **shared** by every concurrent caller (all subagents route through one
        gateway, one child Serena), so teardown is scoped by *why* the call ended:

        - **Timeout** — the child is alive but slow, and sibling calls share the session, so a
          single timeout must not close it (that was the parallel-subagent flakiness: one slow
          TypeScript query tripping the timeout killed every concurrent agent). A child wedged
          so that *every* call times out is still recovered: :meth:`_reap_if_wedged` respawns it
          after :data:`_WEDGE_TIMEOUTS` consecutive timeouts with no intervening success.
        - **Cancellation** — a caller went away (a subagent finished or was cancelled); that
          says nothing about the child's health, so never tear the shared session down.
        - **Any other error** — a genuine transport failure (the child crashed); respawn it.

        Both reap paths are gated on client identity (:meth:`_reap_if_current`), so a burst of
        callers failing on one dead/wedged child respawns it once, not once per caller.

        Raises:
            TimeoutError: If Serena does not respond within the timeout.
        """
        try:
            with (
                self.register_inflight(TOOL_PREFIX + name, self.root or ""),
                anyio.fail_after(serena_dispatch_timeout()) as scope,
            ):
                return await self._dispatch(name, arguments)
        except TimeoutError:
            # The outer deadline fires as a cancellation *inside* :meth:`_dispatch` (caught and
            # re-raised by its ``get_cancelled_exc_class`` handler, never reaped) and only becomes
            # a ``TimeoutError`` here on scope exit. ``scope.cancel_called`` distinguishes a wedged
            # connect/lock from an inner per-call timeout, which is re-raised unchanged.
            if scope.cancel_called:
                msg = f"serena dispatch {name!r} exceeded {serena_dispatch_timeout()}s (connect/lock wedged)"
                raise TimeoutError(msg) from None
            raise

    async def _dispatch(self, name: str, arguments: dict) -> types.CallToolResult:
        """Connect (lock-wait + single-flight connect) then forward one bounded call.

        Runs inside the outer dispatch deadline opened by :meth:`call`; the per-call
        :func:`serena_timeout` bounds only the forward, while the surrounding deadline bounds the
        connect/lock-wait too. Teardown is scoped by why the call ended (see :meth:`call`).

        Cooperative ``anyio.fail_after`` cannot interrupt an ``await`` blocked inside fastmcp's
        stdio read when the child wedges mid-request (issue #30): the read never observes the
        cancellation, so the await never returns and the timeout recovery below is unreachable. An
        out-of-band **watchdog** closes that gap — armed at :func:`serena_hard_deadline` (strictly
        above the per-call timeout), it force-kills the child's process group from the outside,
        closing its stdout so the blocked read finally errors out and the await unwinds here.
        ``hard_killed`` records that we caused it, so whichever exception the unwinding read
        surfaces (a transport error, a converted ``TimeoutError``, or a stray cancellation) is
        normalized to a ``TimeoutError`` and the dead session reaped — never a caller cancellation.
        """
        client = await self._connected_client()
        hard_killed = False

        async def _watchdog() -> None:
            # Independent of the cooperative fail_after the wedged await ignores: sleep past the
            # hard deadline, then kill the child's process group so its stdout closes and the
            # blocked read unwinds. Set the flag *before* the kill so the resulting error is
            # already attributable to us. Cancelled in ``finally`` on every healthy/normal exit.
            nonlocal hard_killed
            await anyio.sleep(serena_hard_deadline())
            pid = self._child_pid
            if pid is None:
                return
            hard_killed = True
            await to_thread.run_sync(_kill_child_group, pid)

        watchdog = asyncio.ensure_future(_watchdog())
        try:
            with anyio.fail_after(serena_timeout()):
                result = await client.call_tool_mcp(name, arguments)
        except TimeoutError:
            if hard_killed:
                raise await self._reap_hard_killed(client, name) from None
            await self._reap_if_wedged(client)
            msg = f"serena call {name!r} timed out after {serena_timeout()}s"
            raise TimeoutError(msg) from None
        except anyio.get_cancelled_exc_class():
            if hard_killed:
                raise await self._reap_hard_killed(client, name) from None
            raise
        except BaseException:
            if hard_killed:
                raise await self._reap_hard_killed(client, name) from None
            await self._reap_if_current(client)
            raise
        else:
            self._consecutive_timeouts = 0
            return result
        finally:
            watchdog.cancel()
            with suppress(BaseException):
                await watchdog

    async def _reap_hard_killed(self, client: Client, name: str) -> TimeoutError:
        """Reap the session a watchdog hard-killed and build the normalized timeout error.

        The child is already dead (its process group was killed), so this discards the dead
        session unconditionally via :meth:`_reap_if_current` — the next call respawns a fresh
        child — and returns the ``TimeoutError`` the caller re-raises. Used for *all* three
        unwinding exception types so the wedge always surfaces as a timeout, never a cancellation.
        """
        await self._reap_if_current(client)
        msg = f"serena call {name!r} hard-killed after {serena_hard_deadline()}s (wedged mid-request)"
        return TimeoutError(msg)

    async def _reap_if_wedged(self, client: Client) -> None:
        """Respawn the shared session when a *single* slow call is not the whole story.

        One timeout leaves a healthy-but-slow child in place for its concurrent siblings. But
        ``is_connected()`` can report a dead child as alive, and a wedged language server can
        accept the connection yet never answer — so a child is also reaped after
        :data:`_WEDGE_TIMEOUTS` consecutive timeouts with no intervening success, restoring
        recovery without letting one slow call disturb siblings. The counter is reset by any
        successful :meth:`call` and inside :meth:`_reap_if_current` on respawn.
        """
        self._consecutive_timeouts += 1
        if self._consecutive_timeouts >= _WEDGE_TIMEOUTS or not client.is_connected():
            await self._reap_if_current(client)

    def call_from_thread(self, name: str, arguments: dict) -> types.CallToolResult:
        """Sync facade for callers running in a worker thread (e.g. health checks)."""
        return from_thread.run(self.call, name, arguments)

    async def list_live_tools(self) -> list[types.Tool]:
        """List tools from the live child (used by the snapshot generator)."""
        client = self._ensure_client()
        async with client:
            return await client.list_tools()

    async def aclose(self) -> None:
        """Terminate the child process, if one was ever started.

        Cancel any in-flight single-flight connect first — outside the lock, since the connect
        task holds it — so a connect that would otherwise complete after shutdown cannot
        orphan a freshly spawned child.
        """
        task, self._connect_task = self._connect_task, None
        if task is not None and not task.done():
            task.cancel()
            with suppress(BaseException):
                await task
        async with self._lock:
            await self._discard_locked()


class _ProxiedSerenaTool(Tool):
    """A snapshot-defined tool whose run() forwards to the gateway, result passed through verbatim."""

    _gateway: SerenaGateway = PrivateAttr()

    async def run(self, arguments: dict) -> ToolResult:
        """Forward to Serena and map the raw CallToolResult 1:1 (content, structured, is_error).

        First consult the per-file capability gate: a tool whose underlying LSP method is
        unsupported for the target file's language (e.g. find_implementations on Python, which
        Pyright does not implement) is refused here — before connecting — with a redirect message.
        """
        bare = self.name.removeprefix(TOOL_PREFIX)
        gate = serena_gate.capability_gate_for(bare)
        if gate is not None and not serena_gate.gate_disabled():
            refusal = gate(arguments.get("relative_path", ""))
            if refusal is not None:
                return ToolResult(content=[types.TextContent(type="text", text=refusal)], is_error=True)
        result = await self._gateway.call(bare, arguments)
        return ToolResult(
            content=result.content,
            structured_content=result.structuredContent,
            is_error=bool(result.isError),
        )


def load_snapshot() -> dict:
    """Load the packaged Serena tool snapshot, or an empty one when not generated yet."""
    resource = files("repo_agent_harness") / _SNAPSHOT_NAME
    if not resource.is_file():
        return {"pin": SERENA_PIN, "tools": []}
    return json.loads(resource.read_text(encoding="utf-8"))


def proxied_tools(gw: SerenaGateway) -> list[Tool]:
    """Build the prefixed, forwarding Tool objects from the static snapshot (no connection)."""
    tools: list[Tool] = []
    for entry in load_snapshot()["tools"]:
        tool = _ProxiedSerenaTool(
            name=TOOL_PREFIX + entry["name"],
            description=entry.get("description"),
            parameters=entry.get("inputSchema") or {"type": "object"},
            output_schema=entry.get("outputSchema"),
        )
        tool._gateway = gw
        tools.append(tool)
    return tools


def generate_snapshot(root: str) -> dict:
    """Launch the pinned Serena once, dump its tool list, and write the packaged snapshot.

    Dev-time command (network: resolves the pin). Returns a summary dict.
    """
    gw = SerenaGateway(root)

    async def _dump() -> list[types.Tool]:
        try:
            return await gw.list_live_tools()
        finally:
            await gw.aclose()

    tools = anyio.run(_dump)
    snapshot = {
        "pin": SERENA_PIN,
        "spec": serena_spec(),
        "tools": [t.model_dump(mode="json", exclude_none=True) for t in tools],
    }
    # dev-time command: writes into the source tree next to this module
    target = Path(__file__).parent / _SNAPSHOT_NAME
    target.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")
    return {"ok": True, "pin": SERENA_PIN, "tool_count": len(tools), "written": str(target)}
