"""Serena gateway: the harness owns, launches, and proxies the pinned Serena MCP server.

Single-server architecture: agents talk to one harness server; Serena's tools are
re-exposed here under the ``serena_`` prefix and forwarded over an MCP client
connection to a child Serena process. The child is launched lazily on the first
serena tool call (never at session start) from a SHA-pinned uvx spec — this module
is the one and only place the pin lives.

Lazy start works via a static tool snapshot: ``serena_tools.json`` (generated by
``repo-agent-harness gateway-snapshot`` against the pinned spec, packaged with the
wheel) serves ``tools/list`` without touching the child. Because Serena is pinned
by commit SHA the snapshot is deterministic; a no-network test guards pin drift.

The stdio transport uses ``keep_alive``, so the Serena process (and its language
servers) survives across calls, and a crashed child is respawned transparently on
the next call.
"""

from __future__ import annotations

import json
import os
from importlib.resources import files
from pathlib import Path
from typing import TYPE_CHECKING

import anyio
from anyio import from_thread
from fastmcp import Client
from fastmcp.client.transports import StdioTransport
from fastmcp.tools import Tool, ToolResult
from pydantic import PrivateAttr

if TYPE_CHECKING:
    from mcp import types

SERENA_PIN = "2449313c0d7427275c4c66aedff7d4881782f713"
SERENA_SPEC_ENV = "REPO_AGENT_HARNESS_SERENA_SPEC"
TOOL_PREFIX = "serena_"
_SNAPSHOT_NAME = "serena_tools.json"


def serena_spec() -> str:
    """Return the Serena uvx requirement spec (env override for local serena dev)."""
    return os.environ.get(SERENA_SPEC_ENV) or f"git+https://github.com/oraios/serena@{SERENA_PIN}"


def serena_args(root: str) -> list[str]:
    """Return the uvx argv to start the pinned Serena MCP server."""
    return [
        "--from",
        serena_spec(),
        "serena",
        "start-mcp-server",
        "--context",
        "claude-code",
        "--project",
        root,
        "--enable-web-dashboard",
        "false",
        "--enable-gui-log-window",
        "false",
    ]


class SerenaGateway:
    """Lazy, crash-tolerant MCP client owning the child Serena process for one repo."""

    def __init__(self, root: str, transport: StdioTransport | None = None) -> None:
        """Prepare the client without connecting; ``transport`` is injectable for tests."""
        self.root = root
        self._client = Client(
            transport or StdioTransport(command="uvx", args=serena_args(root), cwd=root, keep_alive=True)
        )

    async def call(self, name: str, arguments: dict) -> types.CallToolResult:
        """Forward one tool call to Serena (launches the child on first use)."""
        async with self._client:
            return await self._client.call_tool_mcp(name, arguments)

    def call_from_thread(self, name: str, arguments: dict) -> types.CallToolResult:
        """Sync facade for callers running in a worker thread (e.g. health checks)."""
        return from_thread.run(self.call, name, arguments)

    async def list_live_tools(self) -> list[types.Tool]:
        """List tools from the live child (used by the snapshot generator)."""
        async with self._client:
            return await self._client.list_tools()

    async def aclose(self) -> None:
        """Terminate the child process (keep_alive transports outlive sessions otherwise)."""
        await self._client.close()


class _ProxiedSerenaTool(Tool):
    """A snapshot-defined tool whose run() forwards to the gateway, result passed through verbatim."""

    _gateway: SerenaGateway = PrivateAttr()

    async def run(self, arguments: dict) -> ToolResult:
        """Forward to Serena and map the raw CallToolResult 1:1 (content, structured, is_error)."""
        result = await self._gateway.call(self.name.removeprefix(TOOL_PREFIX), arguments)
        return ToolResult(
            content=result.content,
            structured_content=result.structuredContent,
            is_error=bool(result.isError),
        )


def load_snapshot() -> dict:
    """Load the packaged Serena tool snapshot, or an empty one when not generated yet."""
    resource = files("repo_agent_harness") / _SNAPSHOT_NAME
    if not resource.is_file():
        return {"pin": SERENA_PIN, "tools": []}
    return json.loads(resource.read_text(encoding="utf-8"))


def proxied_tools(gw: SerenaGateway) -> list[Tool]:
    """Build the prefixed, forwarding Tool objects from the static snapshot (no connection)."""
    tools: list[Tool] = []
    for entry in load_snapshot()["tools"]:
        tool = _ProxiedSerenaTool(
            name=TOOL_PREFIX + entry["name"],
            description=entry.get("description"),
            parameters=entry.get("inputSchema") or {"type": "object"},
            output_schema=entry.get("outputSchema"),
        )
        tool._gateway = gw
        tools.append(tool)
    return tools


def generate_snapshot(root: str) -> dict:
    """Launch the pinned Serena once, dump its tool list, and write the packaged snapshot.

    Dev-time command (network: uvx resolves the pin). Returns a summary dict.
    """
    gw = SerenaGateway(root)

    async def _dump() -> list[types.Tool]:
        try:
            return await gw.list_live_tools()
        finally:
            await gw.aclose()

    tools = anyio.run(_dump)
    snapshot = {
        "pin": SERENA_PIN,
        "spec": serena_spec(),
        "tools": [t.model_dump(mode="json", exclude_none=True) for t in tools],
    }
    # dev-time command: writes into the source tree next to this module
    target = Path(__file__).parent / _SNAPSHOT_NAME
    target.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")
    return {"ok": True, "pin": SERENA_PIN, "tool_count": len(tools), "written": str(target)}
